name: mywalls
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.7
  json_annotation: ^4.8.1
  objectbox: ^2.1.0
  objectbox_flutter_libs: ^2.1.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: ^6.7.1
  objectbox_generator: ^2.1.0
  retrofit_generator: any
  riverpod_generator: any

flutter:
  uses-material-design: true
